### ISSUE TITLE
Paragraphs within blockquotes are not parsed

### ISSUE THREAD

**Issue by srid** [mmark-md/mmark#72]
```
> This is first paragraph
  
  This is second.
```

The above should normally be rendered as two paragraphs within a single blockquote, but mmark renders them joined together as one paragraph in the blockquote.

**Comment by mrkkrp** [comment]
Well, it doesn't:

```
$ mmark
> First paragraph.

  Second paragraph.
<Ctrl-D>
<blockquote>
<p>First paragraph.</p>
<p>Second paragraph.</p>
</blockquote>

$ mmark --version
mmark 0.0.5.0 UNKNOWN UNKNOWN
using mmark     (library) 0.0.7.2
using mmark-ext (library) 0.2.1.2
```

I'm pretty sure we have unit tests for this, it looks like a very fundamental feature and I used it many times in my posts.

**Comment by srid** [comment]
Oops, you're right. I didn't notice the [buggy CSS](https://css-tricks.com/snippets/css/simple-and-nice-blockquote-styling/) in use.
