### ISSUE TITLE
Parser fails on '_' symbol inside link text

### ISSUE THREAD

**Issue by Termina1** [mmark-md/mmark#75]
The minimal example of this is:
```
[http://twitter.com/thought_sync](http://twitter.com/thought_sync)
```

The error is:
```
ErrorBundle {bundleErrors = TrivialError 27 (Just (Tokens ('_' :| \\\"\\\"))) (fromList [Tokens (']' :| \\\"\\\"),Label ('i' :| \\\"nline content\\\")]) :| [], bundlePosState = PosState {pstateInput = \\\"[http://twitter.com/thought_sync](http://twitter.com/thought_sync).\\\", pstateOffset = 0, pstateSourcePos = SourcePos {sourceName = \\\"rest\\\", sourceLine = Pos 1, sourceColumn = Pos 1}
```

If I remove '_' from text, parser handles this ok:
```
[http://twitter.com/thoughtsync](http://twitter.com/thought_sync)
```

**Comment by mrkkrp** [comment]
Try `<http://twitter.com/thought_sync>`.

**Comment by Termina1** [comment]
Is it a bug or expected behavior? If it’s a bug, I can try to fix it

Best regards, Vyacheslav

**Comment by mrkkrp** [comment]
This is by design, you can read about it in the readme.

**Comment by Termina1** [comment]
This looks incorrect, but ok. Closing issue.

**Comment by mrkkrp** [comment]
MMark does not aim to implement a particular existing Markdown flavor, but rather its own. For example, it is not Common Mark compatible.
